export const OCDSB_SCHOOLS = [
  "A.Y. Jackson Secondary School",
  "Adult High School",
  "Bell High School",
  "Brookfield High School",
  "Cairine Wilson Secondary School",
  "Canterbury High School",
  "Colonel By Secondary School",
  "Earl of March Secondary School",
  "Glebe Collegiate Institute",
  "Gloucester High School",
  "Hillcrest High School",
  "John McCrae Secondary School",
  "Lisgar Collegiate Institute",
  "Longfields-Davidson Heights Secondary School",
  "Maplewood Secondary School",
  "Merivale High School",
  "Nepean High School",
  "Osgoode Township High School",
  "Ottawa Technical Secondary School",
  "Ridgemont High School",
  "Sir Guy Carleton Secondary School",
  "Sir Robert Borden Secondary School",
  "Sir Wilfrid Laurier Secondary School",
  "South Carleton High School",
  "West Carleton Secondary School",
  "Woodroffe High School",
];
